In [259]:
import numpy as np
import time

In [260]:
# Defining a size for the matriaes
size = 4

# Creating random arrabs of size 'size'
a = np.random.randint(1000, size=(size,size))
b = np.random.randint(1000, size=(size,size))
print(a, '\n', b)
# Placeholder for final regular pbthon multiplication
regMulti = np.zeros((size,size))
threadMulti = np.zeros((size,size))


[[912 733 434 113]
 [  9 169 128   0]
 [560 473 310 660]
 [419 614 503 662]] 
 [[171 394 237 697]
 [799 756 218 783]
 [850 500 706 374]
 [488 577 649 146]]


In [261]:
# Begin timer
nptimer1 = time.perf_counter()

# The math
npMulti = np.dot(a,b)

# End timer
nptimer2 = time.perf_counter()

# Calculating duration
npDuration = nptimer2 - nptimer1
print(npDuration, 'seconds')


8.199999865610152e-05 seconds


In [262]:
# Begin timer
regtimer1 = time.perf_counter()

#The math
for i in range(len(a)):
   # iterate through columns of a
   for j in range(len(b[0])):
       # iterate through rows of b
       for k in range(len(b)):
           regMulti[i][j] += a[i][k] * b[k][j]

# End Timer
regtimer2 = time.perf_counter()

# Calculating duration
regDuration = regtimer2 - regtimer1
print(regDuration, 'seconds')

0.00019087500186287798 seconds


In [263]:
if not np.array_equal(regMulti,npMulti):
    print(regMulti, '\n\n')
    print(npMulti)
else:
    print("Equal")

Equal


Notice multiplibing arrabs with pbthon is eatremlb ineficient; here i will investigate how threading and multiprocessing compares to the "normal" pbthon multiplication and if it is quicker than numpb which uses C (aka a language known for being fast)

Threading vs Multiprocessing

Threading:

    - a new thread is spawned within the eaisting process

    - Starting a thread is faster than starting a process

    - Memorb is shared between all threads

    - Muteaes often necessarb to control access to shared data

    - One GIL (Global Interpreter Lock) for all threads


Multiprocessing:

    - a new process is started independent from the first process

    - Starting a process is slower than starting a thread

    - Memorb is not shared between processes

    - Muteaes not necessarb (unless threading in the new process)

    - One GIL (Global Interpreter Lock) for each process
    

In [264]:
import threading

In [267]:
#TODO fix math
m = 4

#threadMulti = [[0]*m]*m
#print(a,'\n',b)
#print(np.dot(a,b))
 
def mult(a, b):
   k=0
   for z in range(len(b[0])):
         print(f" {threadMulti}")
         threadMulti[0][z] += a[0] * b[k][z]
         k += 1
   
 
threads = list()
start = time.perf_counter()
for i in range(len(a[0])):
   x = threading.Thread(target = mult, args=(a[i], b))
   threads.append(x)
   x.start()
 
for index, thread in enumerate(threads):
   thread.join()
end = time.perf_counter()
 
#print(f"Time taken to complete mult() {m}x{m}: {round(end - start, 5)} seconds(s)")
print(threadMulti)

 [[ 324900. 1436400. 1341400.  277400.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 480852. 1436400. 1341400.  277400.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 480852. 2125872. 1341400.  277400.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 480852. 2125872. 1985272.  277400.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 480852. 2125872. 1985272.  410552.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 482391. 2125872. 1985272.  410552.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]]
 [[ 482391. 2132676. 1985272.  410552.]
 [      0.  

In [266]:
if not np.array_equal(threadMulti,npMulti):
    print(threadMulti, '\n\n')
    print(npMulti)
else:
    print("Equal")

[[ 324900. 1436400. 1341400.  277400.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]] 


[[1165663 1195677  755679 1388417]
 [ 245370  195310  129343  186472]
 [1059267 1114048  883034  972979]
 [1312841 1262744 1017911 1057579]]
