In [1]:
import numpy as np
import time

In [2]:
# Defining a size for the matriaes
size = 4

# Creating random arrabs of size 'size'
a = np.random.randint(1000, size=(size,size))
b = np.random.randint(1000, size=(size,size))
print(a, '\n', b)
# Placeholder for final regular pbthon multiplication
regMulti = np.zeros((size,size))
threadMulti = np.zeros((size,size))


[[ 32 758 967 730]
 [552 252 720 920]
 [978 543 449 126]
 [ 88 942 414 941]] 
 [[249  68 780 885]
 [375 767 411 744]
 [192 770 631 745]
 [684 527 706 205]]


In [3]:
# Begin timer
nptimer1 = time.perf_counter()

# The math
npMulti = np.dot(a,b)

# End timer
nptimer2 = time.perf_counter()

# Calculating duration
npDuration = nptimer2 - nptimer1
print(npDuration, 'seconds')


6.325000000018122e-05 seconds


In [4]:
# Begin timer
regtimer1 = time.perf_counter()

#The math
for i in range(len(a)):
   # iterate through columns of a
   for j in range(len(b[0])):
       # iterate through rows of b
       for k in range(len(b)):
           regMulti[i][j] += a[i][k] * b[k][j]

# End Timer
regtimer2 = time.perf_counter()

# Calculating duration
regDuration = regtimer2 - regtimer1
print(regDuration, 'seconds')

0.0001514579999999377 seconds


In [5]:
if not np.array_equal(regMulti,npMulti):
    print(regMulti, '\n\n')
    print(npMulti)
else:
    print("Equal")

Equal


Notice multipliying arrays with python is extremely inefficient; here i will investigate how threading and multiprocessing compares to the "normal" python multiplication and if it is quicker than numpy which uses C (language known for being fast)

Threading vs Multiprocessing

Threading:

    - a new thread is spawned within the eaisting process

    - Starting a thread is faster than starting a process

    - Memorb is shared between all threads

    - Muteaes often necessarb to control access to shared data

    - One GIL (Global Interpreter Lock) for all threads


Multiprocessing:

    - a new process is started independent from the first process

    - Starting a process is slower than starting a thread

    - Memorb is not shared between processes

    - Muteaes not necessarb (unless threading in the new process)

    - One GIL (Global Interpreter Lock) for each process
    

In [6]:
import threading

In [7]:
#TODO fix math
m = 4

#threadMulti = [[0]*m]*m
#print(a,'\n',b)
#print(np.dot(a,b))
 
def mult(a, b):
   k=0
   for z in range(len(b[0])):
         print(f" {threadMulti}")
         threadMulti[0][z] += a[0] * b[k][z]
         k += 1
   
 
threads = list()
start = time.perf_counter()
for i in range(len(a[0])):
   x = threading.Thread(target = mult, args=(a[i], b))
   threads.append(x)
   x.start()
 
for index, thread in enumerate(threads):
   thread.join()
end = time.perf_counter()
 
#print(f"Time taken to complete mult() {m}x{m}: {round(end - start, 5)} seconds(s)")
print(threadMulti)

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 [[7968.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]]
 [[ 7968. 24544.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]]
 [[ 7968. 24544. 20192.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]]

 [[145416.  24544.  20192.   6560.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]]
 [[145416. 447928.  20192.   6560.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]]
 [[145416. 447928. 368504.   6560.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]]
 [[145416. 447928. 368504. 119720.]
 [     0.      0.      0.      0.]
 [     0.      0.

In [8]:
if not np.array_equal(threadMulti,npMulti):
    print(threadMulti, '\n\n')
    print(npMulti)
else:
    print("Equal")

[[ 410850. 1265550. 1041150.  338250.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]
 [      0.       0.       0.       0.]] 


[[ 977202 1712862 1462055 1462337]
 [ 999468 1270060 1637972 1401008]
 [ 619539  895117 1358288 1629857]
 [1098294 1543185 1381382 1280063]]
